version: '3.8'

services:
  ubuntu:
    build: 
      context: .
      args:
        USER_ID: "${HOST_UID:-1001}"
        GROUP_ID: "${HOST_GID:-1001}"
    # user: admin.ackbar
    container_name: lme_development
    user: "${HOST_UID:-1001}:${HOST_GID:-1001}"
    volumes:
      - ../../../LME/:/lme  # Mounts the parent directory to /lme in the container checkout repo as LME
    command: sleep infinity
  lme:
    build:
      context: ../../
      dockerfile: testing/development/Dockerfile
      args:
        USER_ID: "${HOST_UID:-1001}"
        GROUP_ID: "${HOST_GID:-1001}"
    privileged: true
    container_name: lme
    user: "${HOST_UID:-1001}:${HOST_GID:-1001}"
    volumes:
      - ../:/home/admin.ackbar/LME  # Mounts the parent directory to /home/admin.ackbar/LME in the container checkout repo as LME
    command: sleep infinity
    ports:
      - "443:443"
      - "9200:9200"
      - "9300:9300"
      - "5000:5000"
      - "9600:9600"
      - "5601:5601"