version: '3.8'

services:
  ubuntu:
    build: .
    container_name: lme_development
    volumes:
      - ../../../LME/:/lme  # Mounts the parent directory to /app in the container checkout repo as LME
    command: sleep infinity
  lme:
    build:
      context: ../../
      dockerfile: testing/development/Dockerfile
#    user: admin.ackbar
    privileged: true
    container_name: lme
    volumes:
      - ../../../LME/:/home/admin.ackbar/LME  # Mounts the parent directory to /app in the container checkout repo as LME
    command: sleep infinity