name: Burndown Chart 

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - '*'

jobs:
  create_chart:
    runs-on: ubuntu-latest
    
    steps:
    - name: Print a greeting 
      run: echo "Hello, world!"