name: Burndown Chart 

on: 
  workflow_dispatch:
    inputs:
      start_date:
        description: 'Sprint start date (YYYY-MM-DD)'
        required: true
        type: string
      end_date:
        description: 'Sprint end date (YYYY-MM-DD)'
        required: true
        type: string
    
  pull_request:
    branches:
      - '*'

jobs:
  create_chart:
    runs-on: ubuntu-latest
    env:
      UNIQUE_ID:      

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1

    - name: Setup environment variables
      run: |
        echo "UNIQUE_ID=$(openssl rand -hex 3 | head -c 6)" >> $GITHUB_ENV

    - name: Run Docker Build
      run: docker compose -p ${{ env.UNIQUE_ID }} -f testing/project_management/docker-compose.yml build burndown --no-cache
      
    - name: Run Docker Compose
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: docker compose -p ${{ env.UNIQUE_ID }} -f testing/project_management/docker-compose.yml up -d
      
    - name: List docker containers to wait for them to start
      run: |
        docker ps 

    - name: Set up the burndown chart config
      run: |
        cd testing/project_management
        docker compose -p ${{ env.UNIQUE_ID }} exec -T burndown bash -c '
          cat << EOF > /github-projects-burndown-chart/src/github_projects_burndown_chart/config/config.json
          {
            "cisagov": {
              "LME": {
                "query_variables": {
                  "organization_name": "cisagov",
                  "project_number": 68,
                  "column_count": 5,
                  "max_cards_per_column_count": 50,
                  "labels_per_issue_count": 5
                },
                "settings": {
                  "sprint_start_date": "2024-05-01",
                  "sprint_end_date": "2024-05-16",
                  "points_label": "Points: "
                }
              }
            }
          }
          EOF
          sed -i "s/\"github_token\": \"\"/\"github_token\": \"$GITHUB_TOKEN\"/g" /github-projects-burndown-chart/src/github_projects_burndown_chart/config/secrets.json
          cat /github-projects-burndown-chart/src/github_projects_burndown_chart/config/config.json
        '

    - name: Cleanup Docker Compose
      if: always()
      run: |
        cd testing/project_management
        docker compose -p ${{ env.UNIQUE_ID }} down
        docker system prune -a --force