name: Cluster Run 

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-and-test-cluster:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Setup environment variables
        run: |
          echo "AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "AZURE_SECRET=${{ secrets.AZURE_SECRET }}" >> $GITHUB_ENV
          echo "AZURE_CLIENT_SECRET=${{ secrets.AZURE_SECRET }}" >> $GITHUB_ENV
          echo "AZURE_TENANT=${{ secrets.AZURE_TENANT }}" >> $GITHUB_ENV
          echo "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" >> $GITHUB_ENV


      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" \
          -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run Docker Compose
        run: docker-compose -f testing/development/docker-compose.yml up  -d

      - name: List docker containers to wait for them to start
        run: |
          docker ps 

      - name: Execute powershell in container 
        run: |
          set +e  
          cd testing/development
          docker-compose exec -T lme pwsh -Command "& { exit 1 }"
          EXIT_CODE=$?
          echo "Exit code: $EXIT_CODE"
          set -e  
          if [ "$EXIT_CODE" -ne 0 ]; then
            exit $EXIT_CODE
          fi

      - name: Cleanup Docker Compose
        if: always()
        run: |
          cd testing/development
          docker-compose down
