name: Linux Only

on:
  workflow_dispatch:
  pull_request:

jobs:
  build-and-test-linux-only:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Run Docker Compose
        run: docker-compose -f testing/development/docker-compose.yml up  -d

      - name: Execute steps inside ubuntu container
        run: |
          cd testing/development
          docker-compose exec ubuntu bash -c "echo 'Ubuntu container built'"

      - name: Execute steps inside lme container
        run: |
          cd testing/development
          docker-compose exec ubuntu bash -c "cd /home/admin.ackbar/LME/testing/development && /home/admin.ackbar/LME/testing/development/build_docker_lme_install.sh"

      - name: Cleanup Docker Compose
        if: always()
        run: |
          cd testing/development
          docker-compose down
