---
on:
  push:
    branches:
      - unattended-install

jobs:
  unattended_install_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Move files and run script
        run: |
          sudo mkdir -p /opt/lme
          sudo cp -r * /opt/lme/
          cd /opt/lme
          sudo chmod +x "/opt/lme/Chapter 3 Files/unattended_deploy.sh"
          sudo "/opt/lme/Chapter 3 Files/unattended_deploy.sh" unattended
          sudo docker ps
          curl -s --cacert /usr/share/elasticsearch/config/certificates/ca.crt https://127.0.0.1:9200/_cluster/health
          curl -s --cacert /usr/share/elasticsearch/config/certificates/ca.crt https://127.0.0.1:5601/api/status



