---
on:
  push:
    branches:
      - unattended-install

jobs:
  unattended_install_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Move files and run script
        run: |
          sudo mkdir -p /opt/lme
          sudo cp -r * /opt/lme/
          cd /opt/lme
          sudo chmod +x "/opt/lme/Chapter 3 Files/unattended_deploy.sh"
          sudo "/opt/lme/Chapter 3 Files/unattended_deploy.sh" unattended
          sudo docker ps

      - name: Monitor Kibana Docker Container Logs
        run: |
          end=$((SECONDS+120)) # Run for 2 minutes (120 seconds)
          while [ $SECONDS -lt $end ]; do
            KIBANA_CONTAINER=$(docker ps | grep 'docker.elastic.co/kibana/kibana:8.11.1' | awk '{print $1}')
            if [ ! -z "$KIBANA_CONTAINER" ]; then
              echo "Fetching logs for Kibana Container: $KIBANA_CONTAINER at $(date)"
              docker logs $KIBANA_CONTAINER
            else
              echo "Kibana container not found at $(date)"
            fi
            sleep 5
          done



