---
on:
  push:
    branches:
      - unattended-install

jobs:
  unattended_install_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Move files and run script
        run: |
          sudo mkdir -p /opt/lme
          sudo cp -r * /opt/lme/
          cd /opt/lme
          sudo chmod +x "/opt/lme/Chapter 3 Files/deploy.sh"
          sudo "/opt/lme/Chapter 3 Files/deploy.sh" unattended

