---
on:
  push:
    branches:
      - unattended-install

jobs:
  unattended_install_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make script executable and run
        run: |
          chmod +x "Chapter 3 Files/unattended_deploy.sh"
          sudo "Chapter 3 Files/unattended_deploy.sh" unattended

